<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <StartupObject>AooniBatchDecryptor.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Ookii.Dialogs.WinForms" Version="4.0.0" />
  </ItemGroup>
</Project>
